# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5dd29b743f7b128a9071066b845122ef7659e5c3d3230a98dbab3cd08482d4b7c14d2e8e83139b746a8d22d65fca1f97965677e856375c6e19b87b586411f7a9

test:
  secret_key_base: 388aedaad8322fdcf0ced371d7284d8d1c10b85ab086aeef264d9d7cb87d657fbf70506f34993ae100b9d7aedbd94b0a96a17bdff6c0dab44fac9160b5d32256

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
